import React from 'react';
import { google, slack, atlassian, dropbox, shopify, M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11 } from './imports';
import './brand.css';

const Brand = () => (
  <div className=" elx__blog section__padding eternals">
    <h1>Meet Our Eternals</h1>
    <div className="container">
      <div className="photobanner">
          <img src={M1} />
          <img src={M2} />
          <img src={M3} />
          <img src={M4} />
          <img src={M5} />
          <img src={M6} />
      </div>
    </div>
    <div className="container">
      <div className="photobanner">
          <img src={M7} />
          <img src={M8} />
          <img src={M9} />
          <img src={M10} />
          <img src={M11} />
      </div>
    </div>
    <div className="notification-banner">
    <p>	
    SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | SOLD OUT | PHASE 2 COMING SOON | 
    </p>
    </div>
</div>
);

export default Brand;
